apiVersion: v1
kind: ServiceAccount
metadata:
  name: devops-service-account
  namespace: dawnzlight

---

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: devops-role
  namespace: dawnzlight
rules:
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "patch"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: devops-role-binding
  namespace: dawnzlight
subjects:
- kind: ServiceAccount
  name: devops-service-account
  namespace: dawnzlight
roleRef:
  kind: Role
  name: devops-role
  apiGroup: rbac.authorization.k8s.io
